# Generated by Django 4.0.1 on 2022-01-24 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_alter_ride_arrivaltime_alter_ride_endtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='ridedriver',
            field=models.CharField(max_length=128),
        ),
    ]
