# Generated by Django 4.0.1 on 2022-01-25 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_alter_car_cartype'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='carspace',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='cartype',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
