# Generated by Django 4.0.1 on 2022-01-25 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_ride_carspace_alter_car_cartype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relationship',
            old_name='uesr',
            new_name='user',
        ),
    ]
