# Generated by Django 4.0.1 on 2022-01-29 04:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_alter_car_cartype_alter_car_platenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationship',
            name='earlytime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='relationship',
            name='latetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
