# Generated by Django 4.0.1 on 2022-01-24 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='arrivaltime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='ride',
            name='endtime',
            field=models.DateTimeField(),
        ),
    ]
