# Generated by Django 4.0.1 on 2022-01-24 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_alter_ride_ridedriver'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='cartype',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
    ]
