# Generated by Django 4.0.1 on 2022-01-25 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_rename_uesr_relationship_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='cartype',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='car',
            name='plateNumber',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
